### ISSUE TITLE
Task exception (FAWE) 

### ISSUE THREAD

**Issue by Tiippex** [IllgiLP/WorldEditGlobalizer#16]
Hello I have a probling with the latest version of FAWE and WEG.

![image](https://user-images.githubusercontent.com/16509128/118720123-81748880-b829-11eb-8a2d-4b7e4b17a6ad.png)

`[22:32:28 WARN]: [WorldEditGlobalizerBukkit] Plugin WorldEditGlobalizerBukkit v2.0.4 generated an exception while executing task 936
java.lang.NoSuchMethodError: 'com.sk89q.jnbt.CompoundTag com.sk89q.jnbt.CompoundTag.setValue(java.util.Map)'
        at me.illgilp.worldeditglobalizerbukkit.version.v1_13.clipboard.WEGSpongeSchematicWriter_1_13.write1(WEGSpongeSchematicWriter_1_13.java:137) ~[?:?]
        at me.illgilp.worldeditglobalizerbukkit.version.v1_13.clipboard.WEGSpongeSchematicWriter_1_13.write(WEGSpongeSchematicWriter_1_13.java:39) ~[?:?]
        at me.illgilp.worldeditglobalizerbukkit.version.v1_13.WorldEditManager_1_13.writeClipboard(WorldEditManager_1_13.java:121) ~[?:?]
        at me.illgilp.worldeditglobalizerbukkit.version.v1_13.runnable.ClipboardRunnable_1_13.run(ClipboardRunnable_1_13.java:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-703]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-703]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-703]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Tiippex** [comment]
Thanks for the fast fix :)
